---
- name: Set path
  set_fact:
    bash_path: "/home/{{ user }}"
  when: user is defined

- name: Set path
  set_fact:
    bash_path: "/root"
  when: user is not defined

- name: Bash configuration
  template:
    src: "home/user/{{ item }}.j2"
    dest: "{{ bash_path }}/.{{ item }}"
    owner: "{{ user | default('root') }}"
    group: "{{ user | default('root') }}"
  with_items:
    - bashrc
    - bash_aliases

- name: Vim configuration
  template:
    src: etc/vim/vimrc.local.j2
    dest: /etc/vim/vimrc.local
