---
- name: Set hostname
  hostname:
    name: "{{ hostname_override }}"
  when: hostname_override is defined

# May change due to https://github.com/ansible/ansible-modules-core/issues/3523
- name: Install aptitude
  become: true
  apt:
    pkg: aptitude
    state: latest

- name: Update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Find packages to upgrade
  become: true
  shell: aptitude -q -F%p --disable-columns search "~U"
  register: updates
  changed_when: False

- name: List packages to upgrade
  become: true
  debug: msg="{{ updates.stdout_lines | count }} packages to upgrade ({{ updates.stdout_lines | join(', ') }})"
  when: updates.stdout_lines

- name: Upgrade packages
  become: true
  apt:
    upgrade: "{{ apt_upgrade }}"
  when:
    - apt_upgrade

- name: Install base packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ base_packages }}"

- name: Generate locale
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales }}"

- name: Set default locale
  lineinfile:
    path: /etc/default/locale
    state: present
    regexp: '^LANG='
    line: 'LANG="{{ locales[0] }}"'

- name: "Set timezone {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  notify:
    - Restart cron

# Not sure if needed
- name: "Set localtime {{ timezone }}"
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
  notify:
    - Restart cron

- name: Install custom packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ custom_packages }}"
  when: custom_packages is defined

- name: Set sysctl values
  become: true
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ sysctl_file }}"
    state: present
    reload: true
  with_dict: "{{ sysctl_config }}"
