---

- name: Configure dns
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  notify: restart systemd-resolved
  with_items:
    - etc/systemd/resolved.conf
    - etc/resolv.conf

- name: Enable systemd-resolved
  systemd:
    name: systemd-resolved
    state: started
    enabled: true
    daemon-reload: true
