---
- import_tasks: common.yml
  tags:
    - server-setup
    - common

- import_tasks: fail2ban.yml
  tags:
    - server-setup
    - fail2ban

- import_tasks: ntp.yml
  tags:
    - server-setup
    - ntp

- import_tasks: sysstat.yml
  tags:
    - server-setup
    - sysstat

- import_tasks: ssh.yml
  tags:
    - server-setup
    - ssh

- import_tasks: ufw.yml
  tags:
    - server-setup
    - ufw

- name: create user
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/bash
    home: "/home/{{ user }}"
  when: "user is defined"
