- name: Create /root/.ssh directory
  file:
    path: /root/.ssh
    state: directory

- name: Create /etc/ssh directory
  file:
    path: /etc/ssh
    state: directory

- name: Set authorized keys
  authorized_key:
    key: "https://github.com/{{ item }}.keys"
    user: root
  with_items: "{{ github_users }}"
  when: "github_users is defined"

- name: Ssh configuration
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - Restart ssh
