- name: Create /root/.ssh directory
  become: true
  file:
    path: /root/.ssh
    state: directory

- name: Create /etc/ssh directory
  become: true
  file:
    path: /etc/ssh
    state: directory

- name: Set github authorized keys
  authorized_key:
    key: "https://github.com/{{ item }}.keys"
    user: "{{ user | default('root') }}"
  with_items: "{{ github_users }}"
  when: "github_users is defined"

- name: Set authorized keys
  authorized_key:
    key: "{{ item }}"
    user: "{{ user | default('root') }}"
  with_items: "{{ ssh_keys }}"
  when: "ssh_keys is defined"

- name: Sftp users
  no_log: True
  user:
    name: "{{ item.key }}"
    password: "{{ item.value.password|password_hash('sha512') }}"
    home: "{{ item.value.home | default(omit) }}"
    createhome: yes
    update_password: on_create
  with_dict: "{{ sftp_users }}"

- name: Ssh configuration
  become: true
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - Restart ssh

- name: Create root key
  user:
    name: root
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_type: rsa
