---

- name: Install sysstat
  apt:
    pkg: sysstat
    state: latest

- name: Configure sysstat
  template:
    src: etc/cron.d/sysstat.cron.j2
    dest: /etc/cron.d/sysstat
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart sysstat

- name: Enable sysstat logging
  template:
    src: etc/default/sysstat.j2
    dest: /etc/default/sysstat
  notify:
    - Restart sysstat
