---
- name: Sudo group
  group:
    name: sudo
    state: present

- name: Create user
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    home: "/home/{{ user }}"
    createhome: yes

- name: Passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
